name: Unit Tests Workflow

on:
    push:
    branches:
    - 'main'
    pull_request:
    branches:
    - 'develop'


jobs:
    build-and-test:
    runs-on: macos-13
    timeout-minutes: 25
    
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
